tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
tap "jlhonora/lsusb"
tap "mrtazz/oss"
tap "pantheon-systems/external"
tap "pantheon-systems/internal", "git@github.com:pantheon-systems/homebrew-internal.git"
brew "bison"
brew "direnv"
brew "gh"
brew "hadolint"
brew "jq"
brew "libsass"
brew "mysql-client", link: true
brew "optipng"
brew "pv"
brew "re2c"
brew "redis", restart_service: true
brew "rust"
brew "shellcheck"
brew "watchman"
cask "mark-text"
